### ISSUE TITLE
Hot restart (tcp connection hand over)

### ISSUE THREAD

**Issue by benbromhead** [shotover/shotover-proxy#1039] opened 2023-02-09 22:57 UTC
Evalute the work to do this

Need to transfer codec and all transform state per connection as well.
Also hand over sink tcp connections as well!

**Comment by rukai** [comment] 2024-05-30 07:07
duplicate of https://github.com/shotover/shotover-proxy/issues/130

**Closed by rukai** 2024-05-30 07:07 UTC
